# Generated by Django 5.2.4 on 2026-02-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_transaction_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucomaxiloConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=150, verbose_name='Profissional / Empresa')),
                ('descricao_servico', models.CharField(default='Sobreaviso 24h', help_text='Ex: Sobreaviso, Plantão Fixo, Aluguel Equipamento', max_length=150, verbose_name='Descrição do Serviço')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal Fixo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Bucomaxilo',
                'verbose_name_plural': 'Configurações Bucomaxilo',
            },
        ),
        migrations.CreateModel(
            name='BucomaxiloLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_profissional', models.CharField(max_length=150, verbose_name='Profissional')),
                ('descricao_servico', models.CharField(max_length=150, verbose_name='Descrição')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Contrato')),
                ('dias_no_mes', models.IntegerField(default=30, verbose_name='Dias no Mês')),
                ('dias_trabalhados', models.IntegerField(default=30, verbose_name='Dias Trabalhados')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Bucomaxilo',
                'verbose_name_plural': 'Lançamentos Bucomaxilo',
                'ordering': ['nome_profissional'],
            },
        ),
        migrations.CreateModel(
            name='CirurgiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('setor_nome', models.CharField(max_length=150, verbose_name='Setor')),
                ('cargo_nome', models.CharField(max_length=100, verbose_name='Cargo')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Dia')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Dia')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Noite')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noite')),
                ('dias_mes', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Dias no Mês')),
                ('valor_pega_plantao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pega Plantão')),
                ('valor_efetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Efetivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Cirurgia',
                'verbose_name_plural': 'Lançamentos Cirurgia',
                'ordering': ['setor_nome', 'cargo_nome'],
            },
        ),
        migrations.CreateModel(
            name='CirurgiaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Cirurgia Geral Eletiva, Ortopedia Cirúrgica', max_length=150, verbose_name='Nome do Setor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Setor de Cirurgia',
                'verbose_name_plural': 'Setores de Cirurgia',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CirurgiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Cirurgião', max_length=100, verbose_name='Cargo/Função')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Dia)')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Dia)')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Noite)')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Noite)')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='plantoes.cirurgiasetor')),
            ],
            options={
                'verbose_name': 'Configuração de Escala (Cirurgia)',
                'verbose_name_plural': 'Configurações de Escala (Cirurgia)',
            },
        ),
        migrations.CreateModel(
            name='CoordenacaoConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=150, verbose_name='Nome do Funcionário')),
                ('matricula', models.CharField(blank=True, help_text='Ex: Diretor, Vascular, etc.', max_length=100, null=True, verbose_name='Matrícula / Função')),
                ('conselho', models.CharField(blank=True, help_text='Ex: CRM, COREN', max_length=50, null=True, verbose_name='Conselho')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Coordenação',
                'verbose_name_plural': 'Configurações Coordenação',
            },
        ),
        migrations.CreateModel(
            name='CoordenacaoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_funcionario', models.CharField(max_length=150, verbose_name='Funcionário')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula')),
                ('conselho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conselho')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Contrato (Fixo)')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar (Real)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Coordenação',
                'verbose_name_plural': 'Lançamentos Coordenação',
                'ordering': ['nome_funcionario'],
            },
        ),
        migrations.CreateModel(
            name='NefrologiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(help_text='Ex: Hemodiálise S/CDL', max_length=150, verbose_name='Nome do Procedimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('meta_mensal_qtd', models.IntegerField(default=0, help_text='Quantidade estimada para previsão orçamentária', verbose_name='Meta/Média Mensal (Qtd)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Nefrologia',
                'verbose_name_plural': 'Configurações Nefrologia',
            },
        ),
        migrations.CreateModel(
            name='NefrologiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_procedimento', models.CharField(max_length=150, verbose_name='Procedimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('meta_qtd', models.IntegerField(default=0, verbose_name='Meta (Qtd)')),
                ('qtd_realizada', models.IntegerField(default=0, verbose_name='Qtd. Realizada')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Nefrologia',
                'verbose_name_plural': 'Lançamentos Nefrologia',
                'ordering': ['nome_procedimento'],
            },
        ),
        migrations.CreateModel(
            name='ResidenciaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('valor_aula', models.DecimalField(decimal_places=2, default=250.0, max_digits=10, verbose_name='Valor por Aula')),
                ('meta_aulas', models.IntegerField(default=0, help_text='Quantidade esperada para previsão orçamentária', verbose_name='Meta de Aulas (Mensal)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Residência',
                'verbose_name_plural': 'Configurações Residência',
            },
        ),
        migrations.CreateModel(
            name='ResidenciaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('valor_aula', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Aula')),
                ('meta_aulas', models.IntegerField(default=0, verbose_name='Meta Aulas')),
                ('qtd_aulas', models.IntegerField(default=0, verbose_name='Qtd. Aulas Realizadas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Residência',
                'verbose_name_plural': 'Lançamentos Residência',
                'ordering': ['nome_medico'],
            },
        ),
        migrations.CreateModel(
            name='UrgenciaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('setor_nome', models.CharField(max_length=150, verbose_name='Setor')),
                ('cargo_nome', models.CharField(max_length=100, verbose_name='Cargo')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Dia')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Dia')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Noite')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noite')),
                ('dias_mes', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Dias no Mês')),
                ('valor_pega_plantao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pega Plantão')),
                ('valor_efetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Efetivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Urgência',
                'verbose_name_plural': 'Lançamentos Urgência',
                'ordering': ['setor_nome', 'cargo_nome'],
            },
        ),
        migrations.CreateModel(
            name='UrgenciaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Eixo Vermelho, Sala Amarela, UTI', max_length=150, verbose_name='Nome do Setor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Setor de Urgência',
                'verbose_name_plural': 'Setores de Urgência',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UrgenciaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Clínico Geral', max_length=100, verbose_name='Cargo/Função')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Dia)')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Dia)')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Noite)')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Noite)')),
                ('dias_base_mensal', models.DecimalField(decimal_places=2, default=30, help_text='Ex: 30, 24, 15...', max_digits=5, verbose_name='Dias Base (Mês)')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='plantoes.urgenciasetor')),
            ],
            options={
                'verbose_name': 'Configuração de Escala (Urgência)',
                'verbose_name_plural': 'Configurações de Escala',
            },
        ),
        migrations.CreateModel(
            name='TransporteLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('quantidade_viagens', models.PositiveIntegerField(verbose_name='Qtd. Viagens')),
                ('valor_viagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Viagem')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Lançamento de Transporte',
                'verbose_name_plural': 'Lançamentos de Transporte',
                'ordering': ['-competencia'],
                'unique_together': {('company', 'competencia', 'descricao')},
            },
        ),
    ]
