# Generated by Django 5.2.4 on 2025-08-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_company_management_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UnidadeAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome da unidade')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Unidade de Assistência',
                'verbose_name_plural': 'Unidades de Assistência',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LancamentoPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data do plantão')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade de plantonistas')),
                ('tipo_plantao', models.PositiveIntegerField(choices=[(12, '12 horas'), (24, '24 horas')], verbose_name='tipo de plantão')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor unitário do plantão')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='empresa')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantoes.especialidade', verbose_name='especialidade')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantoes.turno', verbose_name='turno')),
                ('unidade_assistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantoes.unidadeassistencia', verbose_name='unidade de assistência')),
            ],
            options={
                'verbose_name': 'Lançamento de Plantão',
                'verbose_name_plural': 'Lançamentos de Plantão',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoMensalPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Mês e Ano do Orçamento')),
                ('valor_orcado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='valor orçado')),
                ('unidade_assistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantoes.unidadeassistencia', verbose_name='unidade de assistência')),
            ],
            options={
                'verbose_name': 'Orçamento Mensal de Plantão',
                'verbose_name_plural': 'Orçamentos Mensais de Plantão',
                'unique_together': {('unidade_assistencia', 'date')},
            },
        ),
    ]
