# Generated by Django 5.2.4 on 2025-08-01 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade de plantonistas')),
                ('tipo_plantao', models.PositiveIntegerField(choices=[(12, '12 horas'), (24, '24 horas')], verbose_name='tipo de plantão')),
                ('valor_plantao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do plantão')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantoes.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data do lançamento')),
                ('valor_realizado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor realizado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='plantoes.orcamentoplantao')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentoplantao',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantoes.turno'),
        ),
        migrations.CreateModel(
            name='UnidadeAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome da unidade de assistência')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentoplantao',
            name='unidade_assistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantoes.unidadeassistencia'),
        ),
    ]
