# Generated by Django 5.2.4 on 2026-06-06 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
        ('plantoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulatorioConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade')),
                ('vinculo', models.CharField(choices=[('EFETIVO', 'Efetivo'), ('PJ', 'PJ / Contrato')], default='PJ', max_length=20, verbose_name='Vínculo')),
                ('ch_mensal', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='CH Mensal (h)')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Ambulatório',
                'verbose_name_plural': 'Configurações Ambulatório',
                'ordering': ['nome_medico'],
            },
        ),
        migrations.CreateModel(
            name='AmbulatorioLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade')),
                ('vinculo', models.CharField(default='PJ', max_length=20, verbose_name='Vínculo')),
                ('ch_mensal', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='CH Mensal (h)')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Contrato')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Ambulatório',
                'verbose_name_plural': 'Lançamentos Ambulatório',
                'ordering': ['nome_medico'],
            },
        ),
        migrations.CreateModel(
            name='AnestesiologiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(help_text='Ex: C/D Plantão, S/D Plantão, Eletivas, Pré-Anestésico', max_length=150, verbose_name='Tipo de Serviço')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. (Dia/Padrão)')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (Dia/Padrão)')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. (Noite)')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor (Noite)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Anestesiologia',
                'verbose_name_plural': 'Configurações Anestesiologia',
            },
        ),
        migrations.CreateModel(
            name='AnestesiologiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('tipo_servico', models.CharField(max_length=150, verbose_name='Tipo de Serviço')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Dia')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Dia')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Noite')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noite')),
                ('dias_mes', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Dias no Mês')),
                ('valor_pega_plantao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pega Plantão')),
                ('valor_efetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Efetivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Anestesiologia',
                'verbose_name_plural': 'Lançamentos Anestesiologia',
                'ordering': ['tipo_servico'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comissao', models.CharField(max_length=150, verbose_name='Nome da Comissão')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Comissão',
                'verbose_name_plural': 'Configurações Comissões',
                'ordering': ['nome_comissao'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_comissao', models.CharField(max_length=150, verbose_name='Comissão')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Previsto')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Comissão',
                'verbose_name_plural': 'Lançamentos Comissões',
                'ordering': ['nome_comissao'],
            },
        ),
        migrations.CreateModel(
            name='CooperativaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cooperativa', models.CharField(max_length=150, verbose_name='Nome da Cooperativa')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição / Serviço')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Cooperativa',
                'verbose_name_plural': 'Configurações Cooperativas',
                'ordering': ['nome_cooperativa'],
            },
        ),
        migrations.CreateModel(
            name='CooperativaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_cooperativa', models.CharField(max_length=150, verbose_name='Cooperativa')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Previsto')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Cooperativa',
                'verbose_name_plural': 'Lançamentos Cooperativas',
                'ordering': ['nome_cooperativa'],
            },
        ),
        migrations.CreateModel(
            name='EndoscopiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=150, verbose_name='Procedimento / Exame')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('meta_mensal_qtd', models.IntegerField(default=0, verbose_name='Meta/Média Mensal (Qtd)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Endoscopia',
                'verbose_name_plural': 'Configurações Endoscopia',
            },
        ),
        migrations.CreateModel(
            name='EndoscopiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_procedimento', models.CharField(max_length=150, verbose_name='Procedimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('meta_qtd', models.IntegerField(default=0, verbose_name='Meta (Qtd)')),
                ('qtd_realizada', models.IntegerField(default=0, verbose_name='Qtd. Realizada')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Endoscopia',
                'verbose_name_plural': 'Lançamentos Endoscopia',
                'ordering': ['nome_procedimento'],
            },
        ),
        migrations.CreateModel(
            name='UltrassonografiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Plantonista', max_length=100, verbose_name='Cargo/Função')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Dia)')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Dia)')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Noite)')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Noite)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Ultrassonografia',
                'verbose_name_plural': 'Configurações Ultrassonografia',
            },
        ),
        migrations.CreateModel(
            name='UltrassonografiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('cargo_nome', models.CharField(max_length=100, verbose_name='Cargo')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Dia')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Dia')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Noite')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noite')),
                ('dias_mes', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Dias no Mês')),
                ('valor_pega_plantao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pega Plantão')),
                ('valor_efetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Efetivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Ultrassonografia',
                'verbose_name_plural': 'Lançamentos Ultrassonografia',
                'ordering': ['cargo_nome'],
            },
        ),
    ]
