# Generated by Django 5.2.4 on 2026-02-04 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_bank_account'),
        ('plantoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('quantidade_viagens', models.PositiveIntegerField(verbose_name='Qtd. Viagens')),
                ('valor_viagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Viagem')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Lançamento de Transporte',
                'verbose_name_plural': 'Lançamentos de Transporte',
                'ordering': ['-competencia'],
                'unique_together': {('company', 'competencia', 'descricao')},
            },
        ),
    ]
