# Generated by Django 5.2.4 on 2026-02-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantoes', '0003_urgencialancamento_urgenciasetor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgenciaconfiguracao',
            name='dias_base_mensal',
        ),
    ]
