# Generated by Django 5.2.4 on 2026-02-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_bank_account'),
        ('plantoes', '0004_remove_urgenciaconfiguracao_dias_base_mensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirurgiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('setor_nome', models.CharField(max_length=150, verbose_name='Setor')),
                ('cargo_nome', models.CharField(max_length=100, verbose_name='Cargo')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Dia')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Dia')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Noite')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noite')),
                ('dias_mes', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Dias no Mês')),
                ('valor_pega_plantao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pega Plantão')),
                ('valor_efetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Efetivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Cirurgia',
                'verbose_name_plural': 'Lançamentos Cirurgia',
                'ordering': ['setor_nome', 'cargo_nome'],
            },
        ),
        migrations.CreateModel(
            name='CirurgiaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Cirurgia Geral Eletiva, Ortopedia Cirúrgica', max_length=150, verbose_name='Nome do Setor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Setor de Cirurgia',
                'verbose_name_plural': 'Setores de Cirurgia',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CirurgiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Cirurgião', max_length=100, verbose_name='Cargo/Função')),
                ('qtd_dia', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Dia)')),
                ('valor_plantao_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Dia)')),
                ('qtd_noite', models.PositiveIntegerField(default=0, verbose_name='Qtd. Plantonistas (Noite)')),
                ('valor_plantao_noite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Plantão (Noite)')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='plantoes.cirurgiasetor')),
            ],
            options={
                'verbose_name': 'Configuração de Escala (Cirurgia)',
                'verbose_name_plural': 'Configurações de Escala (Cirurgia)',
            },
        ),
    ]
