# Generated by Django 5.2.4 on 2026-02-06 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_bank_account'),
        ('plantoes', '0005_cirurgialancamento_cirurgiasetor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NefrologiaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(help_text='Ex: Hemodiálise S/CDL', max_length=150, verbose_name='Nome do Procedimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('meta_mensal_qtd', models.IntegerField(default=0, help_text='Quantidade estimada para previsão orçamentária', verbose_name='Meta/Média Mensal (Qtd)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Nefrologia',
                'verbose_name_plural': 'Configurações Nefrologia',
            },
        ),
        migrations.CreateModel(
            name='NefrologiaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_procedimento', models.CharField(max_length=150, verbose_name='Procedimento')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('meta_qtd', models.IntegerField(default=0, verbose_name='Meta (Qtd)')),
                ('qtd_realizada', models.IntegerField(default=0, verbose_name='Qtd. Realizada')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Nefrologia',
                'verbose_name_plural': 'Lançamentos Nefrologia',
                'ordering': ['nome_procedimento'],
            },
        ),
    ]
