# Generated by Django 5.2.4 on 2026-02-06 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_bank_account'),
        ('plantoes', '0006_nefrologiaconfiguracao_nefrologialancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucomaxiloConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissional', models.CharField(max_length=150, verbose_name='Profissional / Empresa')),
                ('descricao_servico', models.CharField(default='Sobreaviso 24h', help_text='Ex: Sobreaviso, Plantão Fixo, Aluguel Equipamento', max_length=150, verbose_name='Descrição do Serviço')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal Fixo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Bucomaxilo',
                'verbose_name_plural': 'Configurações Bucomaxilo',
            },
        ),
        migrations.CreateModel(
            name='BucomaxiloLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_profissional', models.CharField(max_length=150, verbose_name='Profissional')),
                ('descricao_servico', models.CharField(max_length=150, verbose_name='Descrição')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Contrato')),
                ('dias_no_mes', models.IntegerField(default=30, verbose_name='Dias no Mês')),
                ('dias_trabalhados', models.IntegerField(default=30, verbose_name='Dias Trabalhados')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Bucomaxilo',
                'verbose_name_plural': 'Lançamentos Bucomaxilo',
                'ordering': ['nome_profissional'],
            },
        ),
    ]
