# Generated by Django 5.2.4 on 2026-02-07 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_bank_account'),
        ('plantoes', '0007_bucomaxiloconfiguracao_bucomaxilolancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenciaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.CharField(max_length=150, verbose_name='Nome do Médico')),
                ('valor_aula', models.DecimalField(decimal_places=2, default=250.0, max_digits=10, verbose_name='Valor por Aula')),
                ('meta_aulas', models.IntegerField(default=0, help_text='Quantidade esperada para previsão orçamentária', verbose_name='Meta de Aulas (Mensal)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Residência',
                'verbose_name_plural': 'Configurações Residência',
            },
        ),
        migrations.CreateModel(
            name='ResidenciaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('valor_aula', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Aula')),
                ('meta_aulas', models.IntegerField(default=0, verbose_name='Meta Aulas')),
                ('qtd_aulas', models.IntegerField(default=0, verbose_name='Qtd. Aulas Realizadas')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Residência',
                'verbose_name_plural': 'Lançamentos Residência',
                'ordering': ['nome_medico'],
            },
        ),
    ]
