# Generated by Django 5.2.4 on 2026-02-07 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_bank_account'),
        ('plantoes', '0008_residenciaconfiguracao_residencialancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenacaoConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=150, verbose_name='Nome do Funcionário')),
                ('matricula', models.CharField(blank=True, help_text='Ex: Diretor, Vascular, etc.', max_length=100, null=True, verbose_name='Matrícula / Função')),
                ('conselho', models.CharField(blank=True, help_text='Ex: CRM, COREN', max_length=50, null=True, verbose_name='Conselho')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração Coordenação',
                'verbose_name_plural': 'Configurações Coordenação',
            },
        ),
        migrations.CreateModel(
            name='CoordenacaoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Mês de Referência')),
                ('nome_funcionario', models.CharField(max_length=150, verbose_name='Funcionário')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula')),
                ('conselho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Conselho')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Setor')),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Contrato (Fixo)')),
                ('valor_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a Pagar (Real)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Obs')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Lançamento Coordenação',
                'verbose_name_plural': 'Lançamentos Coordenação',
                'ordering': ['nome_funcionario'],
            },
        ),
    ]
