# Generated by Django 5.2.4 on 2025-08-06 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client company name', max_length=100, unique=True, verbose_name='name')),
                ('management_type', models.CharField(choices=[('publica', 'Gestão Pública (Foco em Orçamento)'), ('particular', 'Gestão Particular (Foco em Lucratividade)')], default='particular', max_length=15, verbose_name='tipo de gestão')),
                ('users', models.ManyToManyField(help_text='Users who can manage this company', related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Account code, e.g., 1.01.01', max_length=20, verbose_name='code')),
                ('name', models.CharField(help_text='Account name, e.g., Product Sales', max_length=100, verbose_name='name')),
                ('account_type', models.CharField(choices=[('R', 'Revenue'), ('E', 'Expense')], max_length=1, verbose_name='account type')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='core.chartofaccounts', verbose_name='parent account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.chartofaccounts', verbose_name='account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='annual amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts', verbose_name='account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('company', 'account', 'year')},
            },
        ),
    ]
