# Generated by Django 5.2.4 on 2025-07-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Transaction',
        ),
    ]
