# Generated by Django 5.2.4 on 2025-08-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(choices=[('R', 'Revenue'), ('D', 'Expense')], max_length=1, verbose_name='account type'),
        ),
    ]
