# Generated by Django 5.2.4 on 2025-08-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_chartofaccounts_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='management_type',
            field=models.CharField(choices=[('Pública', 'Gestão Pública (Foco em Orçamento)'), ('Particular', 'Gestão Particular (Foco em Lucratividade)')], default='particular', max_length=15, verbose_name='tipo de gestão'),
        ),
    ]
