# Generated by Django 5.2.4 on 2025-07-17 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_trasaction_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'verbose_name': 'Chart of Account', 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(choices=[('R', 'Revenue'), ('E', 'Expense')], max_length=1, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='code',
            field=models.CharField(help_text='Account code, e.g., 1.01.01', max_length=20, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='name',
            field=models.CharField(help_text='Account name, e.g., Product Sales', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='core.chartofaccounts', verbose_name='parent account'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Client company name', max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(help_text='Users who can manage this company', related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.chartofaccounts', verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
