# Generated by Django 5.2.4 on 2025-07-20 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chartofaccounts_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='annual amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('account', 'year')},
            },
        ),
    ]
