# Generated by Django 5.2.4 on 2026-01-20 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_created_at_transaction_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do Marcador')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.company')),
            ],
            options={
                'verbose_name': 'Marcador de Nota',
                'verbose_name_plural': 'Marcadores de Notas',
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('color', models.CharField(choices=[('warning', 'Amarelo (Padrão)'), ('info', 'Azul (Informativo)'), ('success', 'Verde (Ideia/OK)'), ('danger', 'Vermelho (Urgente)'), ('secondary', 'Cinza (Arquivo)')], default='warning', max_length=20, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='Lembrar em')),
                ('is_global', models.BooleanField(default=False, verbose_name='Global (Aparece em todas as empresas)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Pública (Para toda equipe)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notetag', verbose_name='Marcador')),
            ],
        ),
    ]
