# Generated by Django 5.2.4 on 2026-01-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('core', '0006_note_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='commercial.sale'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PAID', 'Realizado/Pago'), ('PENDING', 'Pendente/Agendado')], default='PAID', max_length=10, verbose_name='Status da Transação'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='company',
            name='management_type',
            field=models.CharField(choices=[('Pública', 'Gestão Pública (Foco em Orçamento)'), ('Particular', 'Gestão Particular (Foco em Lucratividade)'), ('Particular Plus', 'Gestão Particular Plus (Controle Completo)')], default='particular', max_length=15, verbose_name='tipo de gestão'),
        ),
    ]
