# Generated by Django 5.2.4 on 2026-01-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_remove_sale_account_sale_category_and_more'),
        ('core', '0007_transaction_customer_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.bankaccount', verbose_name='Conta Bancária'),
        ),
    ]
