# Generated by Django 5.2.4 on 2026-01-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_note_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Procedimento')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Padrão')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Data da Venda')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('entry_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Entrada')),
                ('installment_count', models.IntegerField(default=1, verbose_name='Nº de Parcelas (Restante)')),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('MONEY', 'Dinheiro'), ('TRANSFER', 'Transferência')], default='CREDIT_CARD', max_length=20, verbose_name='Forma de Pagto')),
                ('status', models.CharField(choices=[('PENDING', 'Orçamento'), ('CONFIRMED', 'Fechado/Confirmado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.chartofaccounts', verbose_name='Conta de Recebimento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.customer', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.service', verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('corporate_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.company')),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chartofaccounts', verbose_name='Categoria Padrão (Despesa)')),
            ],
        ),
    ]
