# Generated by Django 5.2.4 on 2026-01-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('core', '0007_transaction_customer_transaction_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='account',
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.chartofaccounts', verbose_name='Categoria (Plano de Contas)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chartofaccounts', verbose_name='Categoria Padrão'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Banco Cora, Maquininha Rede, Caixinha', max_length=100, verbose_name='Nome da Conta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.bankaccount', verbose_name='Conta de Destino (Banco/Caixa)'),
        ),
    ]
