# Generated by Django 5.2.4 on 2026-01-31 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_remove_sale_account_sale_category_and_more'),
        ('core', '0008_transaction_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mês de Referência')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta / Limite (R$)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts', verbose_name='Categoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.company')),
            ],
            options={
                'ordering': ['account__name'],
                'unique_together': {('company', 'account', 'month')},
            },
        ),
    ]
